apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-uldlvcxk
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-uldlvcxk:fefb2b2f0044606877b522fb5390dea44da2e571@sha256:82b5643f24635bede5447b679d34c131081af7820775fd4624c14f72c4f7c411
          name: container-image
